vars:
  - spec_params.yaml

stages:
  preprocess:
    cmd: python cli/preprocessing.py
    deps:
      - datasets/bank.csv
    outs:
      - datasets/prepared_data.csv

  first_run:
    cmd: python cli/optuna_best_params.py --max_iter ${train.first_max_iter} --logs ${train.logs}
    deps:
      - datasets/prepared_data.csv
    #outs:
    #  - spec_params.yaml

  second_run:
    cmd: python cli/optuna_best_params.py --max_iter ${train.second_max_iter} --logs ${train.logs}
    deps:
      - datasets/prepared_data.csv
    #outs:
    #  - spec_params.yaml

  train_best_models:
    foreach:
      - ${best_params_max_iter_200}
      - ${best_params_max_iter_500}
    do:
      cmd:  python cli/train.py ${item}
#                  --c ${item.C}
#                  --class_weight ${item.class_weight}
#                  --gamma ${item.gamma}
#                  --kernel ${item.kernel}
#                  --max_iter $
      deps:
        - spec_params.yaml
      outs:
        - models/best_model_${item.max_iter}_iter.pkl


      #echo ${item.class_weight}
      #   cmd: python cli/train.






