vars:
  - spec_params.yaml

stages:
  preprocess:
    cmd: python cli/preprocessing.py
    deps:
      - datasets/bank.csv
    outs:
      - datasets/prepared_data.csv

  first_run:
    cmd: python cli/optuna_best_params.py --max_iter ${train.first_max_iter} --logs ${train.logs}
    deps:
      - datasets/prepared_data.csv
    outs:
      - spec_params_${train.first_max_iter}_max_iter.yaml

  second_run:
    cmd: python cli/optuna_best_params.py --max_iter ${train.second_max_iter} --logs ${train.logs}
    deps:
      - datasets/prepared_data.csv
    outs:
      - spec_params_${train.second_max_iter}_max_iter.yaml

  yaml_merge:
    cmd: python cli/yaml_merge.py 
        --first spec_params_${train.first_max_iter}_max_iter.yaml
        --second spec_params_${train.second_max_iter}_max_iter.yaml
    deps:
      - spec_params_${train.first_max_iter}_max_iter.yaml
      - spec_params_${train.second_max_iter}_max_iter.yaml
    outs:
      - spec_params.yaml

  train_best_models:
    foreach:
      - ${best_params_max_iter_200}
      - ${best_params_max_iter_500}
    do:
      cmd:  python cli/train.py ${item}
      deps:
        - spec_params.yaml
      outs:
        - models/best_model_${item.max_iter}_iter.pkl
        - metrics/metrics_max_iter_${item.max_iter}.csv








